baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Stay safer online'
theme = "tfTheme"

[[header.text]]
text = 'a new ground breaking project'

[minify.tdewolff.css]
keepComments = false

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1

[markup.goldmark.renderer]
  unsafe = true
