baseURL = 'https://3dmakes.ch'
languageCode = 'en-us'
title = '3DMakes'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

################################ English Language ########################
[Languages.en]
languageName = "English"
languageCode = "en"
contentDir = "content/english"
weight = 1

[[Languages.en.menu.main]]
name = "Home"
url = "#header"
weight = 1

[[Languages.en.menu.main]]
name = "Services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "Shop"
url = "#shop"
weight = 3

[[Languages.en.menu.main]]
name = "Quote"
url = "#quote"
weight = 4

[[Languages.en.menu.main]]
name = "Blog"
url = "#blog"
weight = 5

[[Languages.en.menu.main]]
name = "FAQs"
url = "#faqs"
weight = 6

################################ German Language ########################
[Languages.de]
languageName = "Deutsch"
languageCode = "de"
contentDir = "content/german"
weight = 2

[[Languages.de.menu.main]]
name = "Startseite"
url = "#header"
weight = 1

[[Languages.de.menu.main]]
name = "Dienstleistungen"
url = "#services"
weight = 2

[[Languages.de.menu.main]]
name = "Shop"
url = "#shop"
weight = 3

[[Languages.de.menu.main]]
name = "Angebot"
url = "#quote"
weight = 4

[[Languages.de.menu.main]]
name = "Blog"
url = "#blog"
weight = 5

[[Languages.de.menu.main]]
name = "FAQs"
url = "#faqs"
weight = 6

################################ Spanish Language ########################
[Languages.es]
languageName = "Español"
languageCode = "es"
contentDir = "content/spanish"
weight = 3

[[Languages.es.menu.main]]
name = "Inicio"
url = "#header"
weight = 1

[[Languages.es.menu.main]]
name = "Servicios"
url = "#services"
weight = 2

[[Languages.es.menu.main]]
name = "Shop"
url = "#shop"
weight = 3

[[Languages.es.menu.main]]
name = "Cotización"
url = "#quote"
weight = 4

[[Languages.es.menu.main]]
name = "Blog"
url = "#blog"
weight = 5

[[Languages.es.menu.main]]
name = "FAQs"
url = "#faqs"
weight = 6

################################ French Language ########################
[Languages.fr]
languageName = "Français"
languageCode = "fr"
contentDir = "content/french"
weight = 4

[[Languages.fr.menu.main]]
name = "Accueil"
url = "#header"
weight = 1

[[Languages.fr.menu.main]]
name = "Services"
url = "#services"
weight = 2

[[Languages.fr.menu.main]]
name = "Shop"
url = "#shop"
weight = 3

[[Languages.fr.menu.main]]
name = "Devis"
url = "#quote"
weight = 4

[[Languages.fr.menu.main]]
name = "Blog"
url = "#blog"
weight = 5

[[Languages.fr.menu.main]]
name = "FAQs"
url = "#faqs"
weight = 6

################################ Italian Language ########################
[Languages.it]
languageName = "Italiano"
languageCode = "it"
contentDir = "content/italian"
weight = 5

[[Languages.it.menu.main]]
name = "Home"
url = "#header"
weight = 1

[[Languages.it.menu.main]]
name = "Servizi"
url = "#services"
weight = 2

[[Languages.it.menu.main]]
name = "Shop"
url = "#shop"
weight = 3

[[Languages.it.menu.main]]
name = "Preventivo"
url = "#quote"
weight = 4

[[Languages.it.menu.main]]
name = "Blog"
url = "#blog"
weight = 5

[[Languages.it.menu.main]]
name = "FAQs"
url = "#faqs"
weight = 6
